article/urls.py
from django.contrib import admin
from django.urls import path
from article.views import *

app_name = "article"

urlpatterns = [
    path('dashboard/', dashboard, name = "dashboard"),
    path('addarticle/', addarticle, name = "addarticle"),
    path('detailarticle/<int:id>', detailarticle, name = "detailarticle"),
    path('updatearticle/<int:id>', updatearticle, name = "updatearticle"),
    path('deletearticle/<int:id>', deletearticle, name = "deletearticle"),
    path('', articles, name = "articles"),
    path('comment/<int:id>', addComment, name = "addComment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from article.views import *
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from article.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', articles, name = "articles"), #isim vermek çok önemli sakına unutma.
    path('about/', about, name = "about"), #isim vermek çok önemli sakına unutma.
    path('detail/<int:id>', detail, name = "detail"),
    path('articles/',  include('article.urls')), #articles i görürsen git article.urls ye bak ona göre getir.
    path('users/',include('user.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from user.views import *

app_name = "user"

urlpatterns = [
    path('login/', loginUser, name = "login"),
    path('register/', register, name = "register"),
    path('logout/', logoutUser, name = "logout"),
]

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %}>{{ message }}</div>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'articles' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'about' %}"> Hakkımızda <span class="sr-only">(current)</span></a>
      </li>
      
     <!-- <li class="nav-item">
        <a class="nav-link" href="{% url 'article:articles' %}"> Makaleler </a>
      </li>-->
    </ul>
    <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'article:dashboard' %}"> Kullanıcı Paneli </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:logout' %}"> Çıkış Yap </a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:register' %}"> Kayıt Ol </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'user:login' %}"> Giriş Yap </a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>