article/urls.py
from django.contrib import admin
from django.urls import path
from article.views import *

app_name = "article"

urlpatterns = [
    path('dashboard/', dashboard, name = "dashboard"),
    path('addarticle/', addarticle, name = "addarticle"),
    path('detailarticle/<int:id>', detailarticle, name = "detailarticle"),
    path('updatearticle/<int:id>', updatearticle, name = "updatearticle"),
    path('deletearticle/<int:id>', deletearticle, name = "deletearticle"),
    path('', articles, name = "articles"),
    path('comment/<int:id>', addComment, name = "addComment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from article.views import *
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from article.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', articles, name = "articles"), #isim vermek çok önemli sakına unutma.
    path('about/', about, name = "about"), #isim vermek çok önemli sakına unutma.
    path('detail/<int:id>', detail, name = "detail"),
    path('articles/',  include('article.urls')), #articles i görürsen git article.urls ye bak ona göre getir.
    path('users/',include('user.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey(to="auth.User",on_delete = models.CASCADE,verbose_name="Yazar") #auth.userdan alıcak demek 
    title = models.CharField(max_length=50,verbose_name="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Olusturulma Tarihi") #auto_now_add direk olarak o zamanı alır.
    article_image = models.FileField(blank=True,null=True,verbose_name="Makaleye fotograf ekleyin")


    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']
   
class Comment(models.Model):
    article = models.ForeignKey(to=Article, on_delete= models.CASCADE,verbose_name="Makale", related_name= "comments")
    comment_author = models.CharField(max_length=50,verbose_name="İsminiz")
    comment_content = models.CharField(max_length=200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.article

    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from django.forms import ModelForm
from article.models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content','article_image']

article/views.py
from django.shortcuts import render, HttpResponse,redirect,get_object_or_404,reverse
from article.forms import ArticleForm
from django.contrib import messages
from article.models import Article,Comment
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    context = {
        "numbers":[1,2,3,4,5,6,7,8]
    }
    return render(request,"index.html",context= context)
     #burası direk olarak templates içinde aramaya başlıyor belirtildiği gibi.

def addComment(request,id):
    article = get_object_or_404(Article,id=id)
    
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        newComment = Comment(comment_author=comment_author,comment_content=comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse("article:detailarticle",kwargs={"id":id}))


def about(request):
    return render(request,"about.html")

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles= Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()
    return render(request,"articles.html",{"articles":articles})


def detail(request,id):
    return HttpResponse("Detail:"  + str(id))

@login_required(login_url='user:login')
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context={
        "articles" : articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url='user:login')
def addarticle(request):
    form =ArticleForm(request.POST or None, request.FILES or None)
    context={
        "form" : form
    }
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        
        messages.success(request,"Makale başarıyla kayıt edilmiştir.")
        return redirect("index")
    return render(request,"addarticle.html",context)
    
@login_required(login_url='user:login')
def updatearticle(request,id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        
        messages.success(request,"Makale başarıyla güncellendi.")
        return redirect("index")
    context={
        "form":form
    }
    return render(request,"updatearticle.html",context)

@login_required(login_url='user:login')
def deletearticle(request,id):
    article = get_object_or_404(Article, id=id)
    article.delete()
    messages.success(request,"Makale Başarıyla Silindi.")
    return redirect("article:dashboard") # article uygulaması altındaki dashboarda git

@login_required(login_url='user:login')
def detailarticle(request,id):
    #article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article,id=id)
    comments = article.comments.all()
    return render(request,"detailarticle.html",{"article":article,"comments":comments})

templates/about.html
{% extends "bodylay.html" %}

{% block body %}
<h3>Hakkımızda</h3>
<hr>
<p>
    “Hakkımızda” sayfası web sitenizin en önemli sayfalarından biridir. Kişisel blogda blog yazarını; web sitesinde ise grup, dernek ya da firmayı hedef kitlesine tanıtan sayfadır.

Hakkımızda sayfası; tasarımı ve içeriği ile bir duruş sergiler, bu duruş kişisel blogunuzun ya da firmanızın bir yansımasıdır, bir anlamda kimliğinizdir.

Bir firma web sitesinin hakkımızda sayfasında; kurum kültürü ve temel değerleri, tarihi yani hikâyesi, tecrübesi ve öne çıkan farkları, çalışanları, sunduğu hizmet ve ürünlerin tanımı ziyaretçiye özetle anlatılır.

Bu önemli sayfayı; kullanıcı dostu, etkileyici, eksiksiz ve hatta trafik sağlayıcı hale nasıl getirebilirsiniz? Aşağıdaki 14 kuralı göz önünde bulundurarak hazırlayacağınız bir hakkımızda sayfası ile marka imajınızı çok daha güçlü kılabilirsiniz.

Doğru hazırlanmış bir hakkımızda sayfası firmanıza neler kazandırır?
Doğru hazırlanmış bir hakkımızda sayfası firmanıza öncelikle güvenilirlik kazandırır. İyi hazırlanmış bir sayfayla kendinizi daha iyi ifade edebilirsiniz. Aynı ürünü sağlayan, benzer hizmeti veren firmalardan farklılaşırsınız. Potansiyel müşterilerinizin dikkatini çekebilir, yeni müşteriler oluşmasını sağlayabilirsiniz. Uzun vadede yeni müşterileriniz ile satış artışı elde edebilirsiniz.

Tüm bu faydalarının yanı sıra “hakkımızda” ya da “hakkımda” organik trafik yaratan bir sayfa başlığıdır. Bir firmayı Google’da aradığınızda arama sonuçlarında çıkan ilk “Snippet”lardan (link içeren kaynak kodu parçaları) biri büyük olasılıkla hakkımızda sayfanız olacaktır.

Harika bir “hakkımızda” sayfası için 14 kural
1) Hakkımızda sayfasının tasarımı net, açık ve temiz olmalı.

Sayfa; seçilen renkler, yazı fontu, görsel kullanımı, paragraf ve başlık kullanımı ile ziyaretçiye temiz ve net bir görüntü vermeli. Ziyaretçi sayfaya girdiğinde, ele alınan konuları ve başlıkları henüz okumaya başlamadan, karmaşasıyla ziyaretçiyi iter, ziyaretçinin içini sıkar bir görüntüyle karşılaşmamalı.

Ziyaretçi, ana sayfaya giriş yaptığında, firma ile ilgili bilgi almak için bir bakışta “Hakkımızda” butonunu görebilmeli, yani sayfaya ulaşım çok kolay olmalı.

Kullanılan renkler doğru seçilmeli, konular belirleyici başlıklarla ayrılmış, tüm yazı net ve temiz algılanır olmalı. Konular ve yazılar arasında bırakılacak olan beyaz alanlar okuyucuyu dinlendirebilmeli. Dikkat çekmek adına konulan üst üste yazılar ve görseller ziyaretçinin firmanızla çalışma tecrübesinin de bu şekilde olacağını düşündürecektir.

2) Şirket kültürünüzü oluşturan en önemli unsurlardan; vizyonunuz, misyonunuz ve değerlerinizden bahsedin.

Firmanızın gerçekten önem verdiği ve kültürüne yansıtabildiği, dikkatlice hazırlanmış vizyonu ve misyonu varsa hakkımızda sayfasında bunları belirtmelisiniz. Değerleriniz müşterileriniz için de kıymetlidir.

3) Fark yarattığınız noktaların üzerinde durun ve hikâyenizi anlatın.

Kimsiniz? Bu işi neden ve nasıl yapıyorsunuz? Farklılaştığınız noktalar neler? Kısaca ürünleriniz ve hizmetinizde sizi ön plana çıkaracak noktalardan, tercih edilmenize neden olacak unsurlardan bahsedin.

İlk fikir nasıl doğdu, Hedef kitlenizin hangi ihtiyaçlarını keşfederek onlara yanıt olmaya, hizmet sunmaya karar verdiniz. Nasıl buralara geldiniz? Sıkıcı olmadan kısaca hikâyenizden bahsedin. Mütevazı bir dil kullanın.

4) Ekibinizi tanıtın.

Çalışma arkadaşlarınızı sayfanızda paylaşmanız hem ekibinizi motive edecek hem paylaşılacak kadar gurur duyulan bir ekip olduklarını ziyaretçinize gösterecektir. Ekip ruhu başarı için gerekli bir unsurdur. Ekip ruhu olduğu imajı da ziyaretçileri etkileyecektir.

Çalışanların tek tek tanıtımı hatta üst düzey yetkililerin tek tek tanıtımının mümkün olmadığı büyük şirketlerde hep birlikte çekilmiş bir fotoğraf da ekip ruhunu yansıtabilir. Ekibi sosyal ortamlarda gösterebilir, çalışanların herkes gibi ama işlerinde uzman olduklarını yansıtabilirsiniz.

5) “Hakkımda” metniniz yaratıcı ve ilgi çekici olmalı.

Kendinizden ve firmanızdan bahsedecek olan sayfanızda mutlaka “Hakkımızda” başlığını kullanmanıza gerek yok, yaratıcı olabilirsiniz fakat yaratıcılık adına anlaşılmayan bir başlık koymayın. Mesela “Daha da fazlası var!” gibi anlatmak istediğini anlatamayan kelimeler seçmeyin.

Türkiye’nin en çok okunan blogları arasında yer alan bir blog “Hakkımda” yerine “Ben Kimmişim” cümlesi ile sayfasını hazırlıyor ve tüm içeriği aynı tarzda, oldukça yaratıcı ve esprili yazıyor. Sadece bu sayfa ile birçok beğeni, trafik ve kullanıcı kazanıyor.

6) Yazı dilinizi doğru seçin.

Yazı dilinizi hedef kitlenizin özelliklerine göre seçmelisiniz. Örneğin, hedef kitleniz gençlerse daha samimi ve esprili, belli yaş üzeri profesyonellerse biraz daha resmi bir dil kullanmalısınız. Hiçbir zaman hiçbir yazı ortamında aşırılığa kaçmayın. Resmi olacağız derken sıkıcı; samimi olacağız derken laubali olmamalısınız.

7) Firmanızın başarılarından ve şirketinizle ilgili önemli gelişmelerden bahsedin.

Firmanızın elde ettiği başarılar, ödüller, başarıya ait dikkat çekici, doğru veriler inandırıcılığınızı artıracak, müşteride güven oluşturacaktır. Bir sosyal sorumluluk projeniz büyük ses getirdi ve başarıya mı ulaştı, en çok tercih edilen marka ödülünü mü aldınız? Bu sizin için büyük bir gelişme olduğuna göre sizi anlatan sayfada yer kesinlikle yer almalı.

8) Hakkımızda sayfanızı mutlaka fotoğraflar veya videolar ile canlandırın.

Metni çok güzel hazırlanmış dahi olsa insanoğlunun görseli çok daha hızlı algılaması ve görselin her zaman ilgi çekmesi nedenleri ile yazınızda görsel unsurlar kullanmalısınız. Fotoğraf, video gibi görseller yazınıza hareketlilik kazandıracak, metninizin daha çok okunmasını sağlayacaktır. Daha önce de belirttiğimiz gibi “sıkıcı” içeriği kimse okumaz.

9) Sosyal ağlardaki hesaplarınızı bildirmeyi ve link vermeyi unutmayın.

Firmanızı tanıttığınız sayfanızda, firmanızın; Facebook, Twitter, Instagram, gibi sosyal ağlardaki hesaplarını ziyaretçilerinize paylaşmalısınız. Hangi sosyal ortamdan sizi takip etmek istediklerini bırakın kendileri seçsinler. Sosyal medya ikonlarını sayfanızın dikkat çekici bir noktasına koyun. Ziyaretçinizi aklında dahi yoksa en çok kullandığı platformda sizi takip etmeye teşvik edebilirsiniz. Sizi bu noktalardan takip etmese dahi birçok sosyal platformda yer almanız da ziyaretçinizin gözünde bir “güç” göstergesi olacaktır.

10) Müşteri yorumlarına yer verin.

Müşterilerinizin yorumlarını paylaşmak hedef kitlenizi oldukça etkileyecek yöntemlerden biridir. Bir ajanssanız bilinen bir müşterinizin sizin hakkınızdaki olumlu referansı ziyaretçilerinizi etkileyecektir. Kamuoyunda güvenilir imaja sahip bir kurumun size referans olabilmesi size duyulacak güveni arttıracaktır.

Tüm müşterilerinizin yorumlarını eklemek sayfanızı kalabalıklaştıracaktır. Firmanız hakkındaki en etkileyici, en çok sizi anlatan yorumlara “Hakkımızda” sayfanızda yer verebilir bunun avantajlarından faydalanabilirsiniz.

11) İletişim bilgilerinizi paylaşın.

Firmanızı, çalışanlarınızı tanıttınız. Farklılığınızı, hikâyenizi, değerlerinizi paylaştınız. Şimdi hedef kitlenizin size nasıl ulaşacağı konusunda onları bilgilendirmenize sıra geldi. Var olduğunuzu, ulaşılabilir olduğunuzu ve size ulaşılmasından bir sakınca duymadığınızı ziyaretçilerinize göstermelisiniz. Kendinizi ya da firmanızı tanıttığınıza göre adresiniz bu kimlik bilgileri arasında var olabilmeli.
</p>

{% endblock %}

templates/addarticle.html
{% extends "bodylay.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form method="POST" enctype="multipart/form-data">
            <h3>Makale Oluştur</h3>
            <hr>
            {% csrf_token %}
            {{ form.media }}
            {{form|crispy}}
            <button class="btn btn-danger float-right" type="submit">Kaydet</button>
        </form> 
    </div>
</div>
{% endblock %}

templates/articles.html
{% extends "bodylay.html" %}

{% block body %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
                
            <h3>Makaleler</h3>
            <hr>

            <form>
                {% csrf_token %} 
               <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
             <button type="submit" class="btn btn-danger">Ara</button>
            </form>
            
           <hr>
{% if articles %}
        {% for article in articles %}
            
                    
                <!-- Post Content Column -->
                    
                    <!-- Title -->
                    <h3 class="mt-4">
                        <a href="{% url 'article:detailarticle' article.id %}"> {{article.title}}</a> 
                    </h3>
                
                    <!-- Author -->
                    <p class="lead">
                        
                        {{article.author.username}} tarafından yayınlandı
                    </p>
                
                    <hr>
                
                    <!-- Date/Time -->
                    <p>{{article.created_date}}</p>
                
                    <hr>
                
                    
                    {% if article.article_image %}
                    <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
                    {% endif %}
                    
                
                    <hr>
                
                    <!-- Post Content -->
                    <p class="lead">
                        {{article.content|safe}}
                    </p>
                    

                    <a href="/articles/detailarticle/{{article.id}}" class="btn btn-primary text-right">Devamını Oku</a>

                    <hr>
                
                    
                    
        {% endfor %}
        
{% else %}
        <div class="alert alert-danger">
            Bu blogda herhangi bir makale bulunmamaktadır.
        </div>
{% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/bodylay.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>YBBLOG</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    </head>
    <body>
        {% include "includes/navbar.html" %}
        
        <div class="container mt-4">
            {% include "includes/messages.html" %}
            {% block body %}
            {% endblock %}
        </div>
        
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    </body>
</html>

templates/dashboard.html
{% extends "bodylay.html" %}

{% block body %}
        <h3>Kontrol Paneli</h3>
        <hr>

        <p>
            Hoşgeldiniz, <small>{{request.user.username}}</small>
        </p>
        <hr>

        {% if articles %}
            <a href="/articles/addarticle" class="btn btn-danger">Makale Ekle</a>
            <br>
            <br>

            <table class="table table-striped">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Başlık</th>
                    <th>Yazar</th>
                    <th>Tarih</th>
                    <th>İşlemler</th>
                </tr>
                </thead>
                <tbody>
                    {% for article in articles %}
                        <tr>
                            <td>{{article.id}}</td>
                            <td><a href="/articles/detailarticle/{{article.id}}">{{article.title}}</a></td>
                            <td>{{article.author.username}}</td>
                            <td>{{article.created_date}}</td>
                            <td>
                                <a href="/articles/updatearticle/{{article.id}}" class="btn btn-warning">Güncelle</a>
                                <a href="/articles/deletearticle/{{article.id}}" class="btn btn-danger">Sil</a>
                            </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
                <div class="alert alert-danger">
                    Henüz bir makaleniz bulunmuyor...
                </div>
                <a href="/articles/addarticle" class="btn btn-danger">Makale Ekle</a>
        {% endif %}


{% endblock %}

templates/detailarticle.html
{% extends "bodylay.html" %}

{% block body %}
<div class="row">

  <!-- Post Content Column -->
  <div class="col-lg-8">

    <!-- Title -->
    <h3 class="mt-4">{{article.title}}</h3>

    <!-- Author -->
    <p class="lead">
      
      {{article.author.username}} tarafından yayınlandı
    </p>

    <hr>

    <!-- Date/Time -->
    <p>{{article.created_date}}</p>

    <hr>

    
    {% if article.article_image %}
    <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
    {% endif %}
    

    <hr>

    <!-- Post Content -->
    <p class="lead">
        {{article.content|safe}}
    </p>

    <hr>

    <h4>Yorumlar {% if comments %}({{comments.count }}){% endif %}</h4>
    <hr>
    {% if comments %}
    {% for comment in comments  %}
      <div class="media mb-4">
        <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
        <div class="media-body">
          <h5 class="mt-0">{{ comment.comment_author}}</h5>
          {{comment.comment_date}} <br>
          {{comment.comment_content}}
        </div>
      </div>
    {% endfor %}
      
      
    {% else %}
    <div class ="alert alert-danger">
      Bu makaleye herhangi bir yorum yazılmamış,ilk yorum yapan siz olun!
    </div>
    {% endif %}

    <div class="card my-4 container">
      <h5 class="card-header">Yorum Ekle:</h5>
      <div class="card-body">
        <form method = "post" action = "{% url 'article:addComment' article.id %}">
          {% csrf_token %}
          <div class="form-group">
              <label for="formGroupExampleInput">İsim</label>
              <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi girin">
            </div>
          <div class="form-group">
              <label for="formGroupExampleInput">Yorum</label>
              <textarea name = "comment_content" class="form-control" rows="3"></textarea>
          </div>
          <button type="submit" class="btn btn-danger my-3">Ekle</button>
        </form>
      </div>
    </div>

    
  </div>

</div>



{% endblock %}

templates/index.html
{% extends "bodylay.html" %}

{% block body %}
    <div class="jumbotron">
      <h1 class="display-4">Hello, world!</h1>
      <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
      <hr class="my-4">
      <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
      <p class="lead">
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
      </p>
    </div>
    
    <p>
      {% if request.user.is_authenticated %}
          Giriş Yapılmış, {{request.user.username}}
      {% else %}
          Giriş Yapılmamıştır.
      {% endif %}
    </p>


    <p>
      {% for element in numbers %}
          <li>{{element}}</li>
      {% endfor %}
      
    </p>
{% endblock %}

templates/login.html
{% extends "bodylay.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Giriş Yap</button>
        </form>
    </div>
</div>

{% endblock %}

templates/register.html
{% extends 'bodylay.html' %}
{% load crispy_forms_tags %}


{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Kayıt Ol</button>
        </form>
    </div>
</div>
{% endblock %}

templates/updatearticle.html
{% extends "bodylay.html" %}
{% load crispy_forms_tags %}

{% block body %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <form method="POST" enctype="multipart/form-data">
            <h3>Makale Güncelle</h3>
            <hr>
            {% csrf_token %}
            {{ form.media }}
            {{form|crispy}}
            <button class="btn btn-danger float-right" type="submit">Güncelle</button>
        </form> 
    </div>
</div>
{% endblock %}